# Generated by Django 4.0.1 on 2022-02-10 21:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_cliente',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
